import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: '项目概述',
      label: '项目概述',
    },
    {
      type: 'doc',
      id: '快速开始',
      label: '快速开始',
    },
    {
      type: 'doc',
      id: 'API参考',
      label: 'API 参考',
    },
    {
      type: 'doc',
      id: '认证与授权',
      label: '认证与授权',
    },
    {
      type: 'category',
      label: '核心架构',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '核心架构',
        },
      ],
    },
    {
      type: 'category',
      label: '文档模型',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '文档模型',
        },
      ],
    },
    {
      type: 'category',
      label: '数据操作',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '数据操作',
        },
      ],
    },
    {
      type: 'category',
      label: '协作与工作流',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '协作与工作流',
        },
      ],
    },
    {
      type: 'category',
      label: '计费与租户管理',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: '计费与租户管理',
        },
      ],
    },
    {
      type: 'doc',
      id: '扩展与集成',
      label: '扩展与集成',
    },
    {
      type: 'doc',
      id: '开发与部署',
      label: '开发与部署',
    },
    {
      type: 'doc',
      id: '故障排除与最佳实践',
      label: '故障排除与最佳实践',
    },
  ],
};

export default sidebars;
